name: Build
on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 12, 13, 14]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for SonarQube
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1
        if: ${{ matrix.java == '11' }}
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B -Doverlord.version.suffix=+ci-${{ github.run_number }} package --file pom.xml
      - name: Upload agent jar
        uses: actions/upload-artifact@v1
        if: ${{ matrix.java == '11' }}
        with:
          name: Overlord Agent
          path: overlord-agent/target/overlord-agent.jar
      - name: Upload server jar
        uses: actions/upload-artifact@v1
        if: ${{ matrix.java == '11' }}
        with:
          name: Overlord Server
          path: overlord-server/target/overlord-server.jar
      - name: Run sonarqube
        if: ${{ matrix.java == '11' }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://torchmind.com/sonarqube/
          -Dsonar.projectKey=overlord
